### ISSUE TITLE
Why do we need this controller?

### ISSUE THREAD

**Issue by mvladev** [gardener/hvpa-controller#18]
What's lacking in the current HPA / VPA which requires such orchestration over them?

All examples I see mentions of CPU and Memory only.

**Comment by amshuman-kr** [comment]
> What's lacking in the current HPA / VPA which requires such orchestration over them?

1. HPA and VPA are recommended to be mixed only in case HPA is used for custom/external metrics as mentioned [here](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#limitations-of-beta-version). But in some scenarios it might make sense to use them both even for CPU and memory (e.g. `kube-apiserver` or ingress etc.)

1. VPA updates the pods directly (via webhooks) which may confuse HPA as it may not see the changes in the upstream `targetRefs`.

1. Support for configurable (at the resource level) threshold levels to trigger VPA (and possibly HPA) updates.

1. Support flexibly update policy (Off/Auto/ScaleUp/ScaleOut).

1. Custom resource support for VPA updates.
   * At the beginning, this would be with some well-defined annotations to describe which part of the CRD to update the resource requests.
   * But eventually, we can think of proposing a `Resource` subresource along the lines of `Scale` subresource.

**Comment by amshuman-kr** [comment]
I have added the same points in the main README.md in #29 and also listed the same with current status in the roadmap #30.

@mvladev Can we close this issue? Do you have further comments/suggestions?

**Comment by mvladev** [comment]
> VPA updates the pods directly (via webhooks) which may confuse HPA as it may not see the changes in the upstream targetRefs.

What? HPA only gets the [scale subresource ](https://github.com/kubernetes/kubernetes/blob/7e4c3096fe71afc6a23c273b3309ed5db7289d8c/pkg/controller/podautoscaler/horizontal.go#L632) and updates accordingly. It uses the metrics API for getting the actual resources

> But eventually, we can think of proposing a Resource subresource (per container) along the lines of Scale subresource.

Why would that be needed? The `Scale` subresource already provides a [label selector](https://github.com/kubernetes/api/blob/21721929cffa4119565dd1922a54a3e38c440f85/autoscaling/v1/types.go#L141-L146) which can be used to fetch pods associated with that subresource. CRDs don't support setting this yet, though.

**Comment by amshuman-kr** [comment]
> > VPA updates the pods directly (via webhooks) which may confuse HPA as it may not see the changes in the upstream targetRefs.

> What? HPA only gets the [scale subresource](https://github.com/kubernetes/kubernetes/blob/7e4c3096fe71afc6a23c273b3309ed5db7289d8c/pkg/controller/podautoscaler/horizontal.go#L632) and updates accordingly. It uses the metrics API for getting the actual resources

Of course, HPA updates the scale subresource. The trouble is in computing the desired replicas. If VPA recommendation is also being applied then there could be over-provisioning. This in itself is not a problem as such. But it could lead to further unnecessary rebalancing in scaling by either or both HPA and VPA. This would be undesirable. Especially, for `kube-apiserver`.

**Comment by amshuman-kr** [comment]
>> But eventually, we can think of proposing a Resource subresource (per container) along the lines of Scale subresource.

> Why would that be needed? The Scale subresource already provides a [label selector](https://github.com/kubernetes/api/blob/21721929cffa4119565dd1922a54a3e38c440f85/autoscaling/v1/types.go#L141-L146) which can be used to fetch pods associated with that subresource. CRDs don't support setting this yet, though.

This is for updating the resource requests directly on the `targetRef`. Similar, to how HPA does for replicas via the `Scale` subresource. But this is longer term. Not for now.

**Comment by amshuman-kr** [comment]
I hope the clarification above addresses the questions. Closing this issue.
