### ISSUE TITLE
[BUG] Finalizers are not needed

### ISSUE THREAD

**Issue by mvladev** [gardener/hvpa-controller#31]
As HVPA is operating only on K8S resources those finalizers are not needed
https://github.com/gardener/hvpa-controller/blob/a336e86111bbd5ec87f5a749003ba39b4735261e/controllers/hvpa_controller.go#L241-L277

**Comment by amshuman-kr** [comment]
👍 I think we can remove the finalizers.

**Comment by ggaurav10** [comment]
If we agree with the reasoning [here](https://github.com/gardener/hvpa-controller/issues/32#issuecomment-532040145) to use internal cache, then we would need the finalisers.

WDYT? @mvladev @amshuman-kr
