### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by vpnachev** [gardener/hvpa-controller#55]
**Describe the bug:**
This controller is generating huge amount of logs and most of them are unusable because context is missing, e.g.
```bash
I0214 20:32:30.258276       1 hvpa_controller.go:740] controller/hvpa "level"=2 "msg"="Checking if need to scale vertically"  
I0214 20:32:30.258316       1 hvpa_controller.go:806] controller/hvpa "level"=2 "msg"="VPA"  "minutes after last scaling"=153722867.28091294 "target cpu"="300m" "target mem"="1G" "vpaWeight"=100
I0214 20:32:30.258336       1 hvpa_controller.go:955] controller/hvpa "level"=2 "msg"="VPA"  "vpa recommends changes?"=false
I0214 20:32:30.258412       1 hvpa_controller.go:1029] controller/hvpa "level"=1 "msg"="Reconciling"  "hvpa"="etcd-main"
I0214 20:32:30.359044       1 vpa_util.go:98] controller/hvpa "level"=2 "msg"="VPA spec sync"  "HVPA"="etcd-main" "VPA"="etcd-main-dgvkr"
I0214 20:32:30.359133       1 hvpa_controller.go:740] controller/hvpa "level"=2 "msg"="Checking if need to scale vertically"  
I0214 20:32:30.359175       1 hvpa_controller.go:806] controller/hvpa "level"=2 "msg"="VPA"  "minutes after last scaling"=153722867.28091294 "target cpu"="300m" "target mem"="1G" "vpaWeight"=0
I0214 20:32:30.359199       1 hvpa_controller.go:955] controller/hvpa "level"=2 "msg"="VPA"  "vpa recommends changes?"=false
I0214 20:32:30.436004       1 hvpa_controller.go:1029] controller/hvpa "level"=1 "msg"="Reconciling"  "hvpa"="etcd-events"
I0214 20:32:30.558780       1 vpa_util.go:98] controller/hvpa "level"=2 "msg"="VPA spec sync"  "HVPA"="etcd-events" "VPA"="etcd-events-9pprc"
I0214 20:32:30.558877       1 hvpa_controller.go:740] controller/hvpa "level"=2 "msg"="Checking if need to scale vertically"  
I0214 20:32:30.558917       1 hvpa_controller.go:806] controller/hvpa "level"=2 "msg"="VPA"  "minutes after last scaling"=153722867.28091294 "target cpu"="300m" "target mem"="1G" "vpaWeight"=0
I0214 20:32:30.558940       1 hvpa_controller.go:955] controller/hvpa "level"=2 "msg"="VPA"  "vpa recommends changes?"=false
```

Some of the log messages contains the name of the targeted component, but not the namespace so it is not very helpful.
These logs has to be of level `debug` and not visible by default.

**Expected behaviour:**
To have a clear and short info logs with the necessary context, so that the subjects can be identified.

**How To Reproduce (as minimally and precisely as possible):**
Run Gardener v1.0.4 landscape with HVPA featureGate enabled.

**Logs:**
See above. 
The log rate is high.
```bash
$  kubectl -n garden  logs hvpa-controller-585db5fdc8-mkrj6 --since 10m | wc -l 
8879
```

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Hvpa-controller version/commit ID: v0.2.0
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

**Comment by ggaurav10** [comment]
Logs were enhanced in PR #51 which is part of release v0.2.0
The logs lines in the bug report [don't match](https://github.com/gardener/hvpa-controller/blob/v0.2.0/controllers/hvpa_controller.go#L1359) release 0.2.0, and appear to be from an [earlier release](https://github.com/gardener/hvpa-controller/blob/0.1.0/controllers/hvpa_controller.go#L1029).

Please reopen the issue in case there are any more suggestions for enhancement.
Thanks.
