### ISSUE TITLE
Cut a new release with the updated Kubernetes dependencies

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/hvpa-controller#87]
**What you would like to be added:**
As of today they latest release is v0.3.1. v0.3.1 still vendors Kubernetes dependencies that are not with go modules friendly tags.

https://github.com/gardener/hvpa-controller/blob/c9c6e5f67b1e4b013464743072859e936eaaab6d/go.mod#L10-L13

So for this every project that vendors gardener/hvpa-controller@v0.3.1 has to put unnecessary replace statements. For example for gardener/gardener, see:

https://github.com/gardener/gardener/blob/d9d79a4bd84b5e5679369817c7031358e202f7dd/go.mod#L54

and 

https://github.com/gardener/gardener/blob/d9d79a4bd84b5e5679369817c7031358e202f7dd/go.mod#L84

I see that the Kubernetes dependencies are updated in hvpa-controller@master. I would like to ask for a new release of hvpa-controller with the updated Kubernetes dependencies so that projects like gardener/gardener to adopt the new hvpa-controller version and eventually get rid of the replace statements.

**Why is this needed?:**
To prevent replace statements in projects vendoring hvpa-controller@v0.3.1.

**Comment by ialidzhikov** [comment]
@shreyas-s-rao any news?

**Comment by ialidzhikov** [comment]
In https://github.com/gardener/gardener/issues/5222 we saw that because of this issue (there is no release with updated client-go dependency), hvpa-controller cannot support projected `ServiceAccount` tokens. To enable this, we need new release from hvpa-controller@master where the client-go dependency is already updated. Hence:
/priority 2
/assign @shreyas-s-rao @voelzmo

**Comment by rfranzke** [comment]
Awesome, thanks for opening this issue @ialidzhikov, I missed that the `master` branch of `hvpa-controller` already uses a new `client-go` version required for the token reloading.
Yes, apparently only a new release is missing. According to @amshuman-kr the changes seem to be minimal, so @gardener/hvpa-controller-maintainers please focus on getting this new release cut.

**Comment by ashwani2k** [comment]
Noted will work on it this week.

**Comment by shreyas-s-rao** [comment]
HVPA [v0.4.0 released](https://github.com/gardener/hvpa-controller/releases/tag/v0.4.0)
/close
